### ISSUE TITLE
treatment display

### ISSUE THREAD

**Issue by myrmoteras** [punkish/zenodeo#8]
by chance I ended up in this treatment
https://ocellus.punkish.org/blr.html?treatmentId=0381406C3614484CFF67032FE7A9FA82

there are some issue to be aware of.
First, if there is a new species, there is no "undefined". it is either the authority given, or then the authors from the paper.

Citation of the papers should be done in a way it is standard in this community, beginning, with author, year, title, journal, volume, issue, pagenmubers

These are sensitive issue and it would be said to see the powerful tool lessend because of such UI issues

![image](https://user-images.githubusercontent.com/4609956/59064954-dbcde600-88ab-11e9-94c8-ed3572aa597e.png)

**Comment by punkish** [comment]
There are many issues in this "issue". Please keep only one item, as focused as possible, in one issue. For now, I have separated this into separate issues and am closing this issue:

- there is no "undefined". it is either the authority given, or then the authors from the paper: see issue #11 

- citation style: see issue #12
