### ISSUE TITLE
author search in ocellus 3

### ISSUE THREAD

**Issue by myrmoteras** [punkish/zenodeo#9]
searching for an author in ocellus 3 provides an intriguing array of results, most become obvious after a while. 
In a sense, it would be helpful to keep it, but may be it can be structured according to where the name occurs?

**Comment by punkish** [comment]
@myrmoteras you can't really search for author in Ocellus3 at this time. When you type an author's name, it is actually a full text search so you get all matches where that string appears, whether or not it is an author. When more granular search (against separate fields) is implemented then yes, you will be able to focus the authors search against the authors fields.
